name: Build and Deploy
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-publish-python-module:
    name: Build and publish python module to pypi
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.8
        with:
          pypi_token: ${{ secrets.pypi_password }}
